# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build
      - run: git clone https://user:${{ secrets.GITHUB_TOKEN }}@github.com/pegaxp/pegaxp.git
      - working-directory: ./pegaxp
        run: |
          ls | grep -v CNAME | xargs rm -r
          mv -v ../docs/.vuepress/dist/* .
          git config --global user.email "ianlucas_ferreira@hotmail.com"
          git config --global user.name "Ian Lucas"
          git add --all
          git commit -m "Automated deployment"
          git config -l
          git push
