# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build
      - run: git clone https://github.com/pegaxp/pegaxp.git
      - run: cd pegaxp
      - run: ls | grep -v CNAME | xargs rm
      - run: mv -v ../docs/.vuepress/dist/* .
      - run: git add --all
      - run: git commit -m "Automated deployment"
      - run: git push
